export const GET_CATEGORY='GET_CATEGORY'

export const GET_BRANDS='GET_BRANDS'

export const GET_BANNER='GET_BANNER'

export const GET_ATTRIBUTE_BY_CATID='GET_ATTRIBUTE_BY_CATID'

export const GET_PRODUCT_LIST='GET_PRODUCT_LIST'