export const GET_CATEGORY='GET_CATEGORY'

export const GET_BRANDS='GET_BRANDS'

export const GET_BANNER='GET_BANNER'

export const GET_ATTRIBUTE_BY_CATID='GET_ATTRIBUTE_BY_CATID'

export const GET_PRODUCT_LIST='GET_PRODUCT_LIST'

export const GET_HOME_PAGE_DATA='GET_HOME_PAGE_DATA'

export const GET_TRENDS_ALERT='GET_TRENDS_ALERT'

export const GET_SEASONAL_DECOR='GET_SEASONAL_DECOR'

export const GET_UPGRADE_WORK='GET_UPGRADE_WORK'

export const GET_KITCHEN_AND_DINING='GET_KITCHEN_AND_DINING'

export const GET_ACTIVEWEAR='GET_ACTIVEWEAR'

export const GET_HOME_PAGE_NEW='GET_HOME_PAGE'

export const GET_PRODUCT_PAGE='PRODUCT_PAGE'

export const GET_SELLER_DATA='GET_SELLER_DATA'

export const GET_MY_PROFILE_DATA='GET_MY_PROFILE_DATA'

export const GET_SIMILAR_PRODUCTS='GET_SIMILAR_PRODUCTS'

export const GET_SIGN_IN='GET_SIGN_IN'

export const GET_SIGN_UP='GET_SIGN_UP'

export const GET_ADD_TO_CART='GET_ADD_TO_CART'

export const GET_CART='GET_CART'

export const GET_DELETE_CART='GET_DELETE_CART'

export const GET_LOCAL_DATA='GET_LOCAL_DATA'

export const GET_ADD_TO_WISHLIST='GET_ADD_TO_WISHLIST'

export const GET_WISH_LIST='GET_WISH_LIST'

export const REMOVE_FROM_WISHLIST='REMOVE_FROM_WISHLIST'

export const GET_USER_ADDRESS='GET_USER_ADDRESS'

export const GET_SELLER_PRODUCTS='GET_SELLER_PRODUCTS'

export const GET_AVAILABLE_COUPONS='GET_AVAILABLE_COUPONS'

export const GET_COUNTRY_LIST='GET_COUNTRY_LIST'

export const ADD_USER_ADDRESS='ADD_USER_ADDRESS'

export const GET_NOTIFICATION='GET_NOTIFICATION'

export const GET_CARTQUANTITY='GET_CARTQUANTITY'

export const GET_DELETE_ADDRESS='GET_DELETE_ADDRESS'

export const GET_CHANGE_PASSWORD='GET_CHANGE_PASSWORD'
